export * from './product';
export * from './order';
export * from './review';
export * from './brand';
export * from './cart';
export * from './vendor';
export * from './image';
export * from './price';
export * from './shipping';
export * from './forms';
export * from './payment';
export * from './policy';
export * from './support';
export * from './message';
export * from './context';
export * from './wishlist';
export * from './variant';

// Explicitly re-export only one version of each conflicting type
export type { Category } from './category';
export type { CategoryResponse } from './api';
export type { CouponResponse } from './api';
export type { SearchResults } from './api';
export type { Notification } from './notification';
export type { PaymentMethod } from './paymentMethod';
export type { AnalyticsData } from './dashboard';
export type { User, UserRole } from './user';
export { USER_ROLES, getUserRoles } from './user';
export { ApiMessage } from './admin';
export type { AdminUser, UserRoleUpdateRequest, UserDisabledUpdateRequest } from './admin';
export * from './admin';
export type { LowStockProduct } from './admin';
